HOME = {
"en": {
 "path": "/", "alt": "/ar/",
 "title": "Ahmed Esmat — Dubai Real Estate & Business Investment Advisory",
 "meta": "Independent advisory for investors and business owners in Dubai. Define your goals, capital and risk first — then decide whether, where, when and why to invest.",
 "h1": "Start with the investment decision. Not the property.",
 "lede": "I don't start by showing you a property. I start by understanding your goals, capital, investment horizon and risk profile — then we determine where, when and why you should invest.",
 "cta1": ("/investor-assessment/", "Start your investment assessment"), "cta2": ("/projects/", "Compare projects"),
 "cta_note": "Around 4 minutes. No obligation, no sales call unless you ask for one.",
 "ledger": [("Whether", "Property is one use of capital, not the default."), ("Where", "Community and future supply shape returns more than finishes."),
            ("When", "Launch, mid-build or ready: each trades price against risk."), ("Why", "Growth, income, a family home or diversification.")],
 "s1_h": "Don't start with the property. Start with the investor.",
 "s1": ["<b>I don't sell you a property. I help you decide whether, where, when and why to buy one.</b>",
        "In Dubai, most buying journeys begin with a launch, a brochure and a deadline. The buyer then works backwards to justify it. I reverse the order. We start with what your capital needs to achieve, when you'll need access to it, and how your plans hold up if a handover slips or the market cycle turns. Once that's clear, the choice of project becomes a reasoned decision rather than a bet."],
 "q_h": "Four questions before any property",
 "q": [("Whether", "Sometimes the stronger return sits inside your existing business, or the money needs to stay liquid. We say so when it's true."),
       ("Where", "Community, future supply, and who the eventual tenant or buyer will be shape performance more than floor plans."),
       ("When", "Launch, mid-construction, or ready. Each entry point carries a different trade-off between price, liquidity and risk."),
       ("Why", "Capital growth, rental income, a family home, or diversification away from your business. The objective changes which project fits.")],
 "steps_h": "How an engagement works",
 "steps": [("Investment assessment", "A short set of questions on capital, objective, horizon, risk tolerance and payment preference."),
           ("Suitable scenarios", "A small number of options matched to your profile — specific projects, a unit type, a timing strategy, or a non-property alternative."),
           ("Structured comparison", "Shortlisted projects compared on the same criteria: developer, location, payment plan, handover, supply, liquidity and risks."),
           ("A documented recommendation", "You leave with written reasoning, not just a name — so you know why, and can test it yourself.")],
 "opp_h": "Opportunities under analysis",
 "opp": [("/villa-projects-dubai/", "Villa projects", "New and established villa communities across Dubai."),
         ("/off-plan-townhouses-dubai/", "Townhouses", "A lower entry point into family communities, with a different rental and resale profile to villas."),
         ("/projects/elysian-mansions-tilal-al-ghaf/", "Luxury real estate", "Mansions and signature homes, where scarcity and location outweigh price per square foot."),
         ("/off-plan-properties-dubai/", "Off-plan", "Projects under construction with staged payment plans, assessed with realistic assumptions on delivery and exit.")],
 "cmp_h": "Compare by suitability, not by brochure",
 "cmp": "You won't find a 9/10 score here, or a claim that any project is \"the best\". A project that suits an income-focused investor may be wrong for someone targeting capital growth over five years. Each project page sets out strengths, risks, and who it suits — and who it doesn't.",
 "nb_h": "Sometimes the right answer isn't property",
 "nb": ["If your business earns a high return on every dirham reinvested, a stronger acquisition system or a higher conversion rate may outperform a down payment on a villa. If you'll need liquidity in two years, a project handing over in four is a mismatch regardless of its merits.",
         "I treat real estate as one possible use of capital and compare it honestly against the alternatives available to you."],
 "bio_h": "A business operator's view of capital",
 "bio": ["Around ten years in performance marketing, customer acquisition and conversion optimisation — across luxury real estate, healthcare, education and e-commerce — taught me to judge capital by one question: how hard is it working, and what else could it be doing?",
         "In one engagement, a client's conversion rate moved from 2–3% to around 9%. That's the lens I bring to every investment conversation."],
 "faq_h": "Questions investors ask",
 "faqs": [("Do you sell property?", "My role is to help you reach the right decision. If you decide to buy, I'll explain clearly how the transaction is handled, which licensed party executes it, and any commercial relationship involved."),
          ("Can you guarantee returns?", "No — and no one honestly can. I set out the factors that drive returns and risk so your decision rests on evidence, not promises."),
          ("I'm not sure I want to buy yet. Is this still useful?", "That's the best time to start. Many clients begin with \"should I buy at all?\" — and some conclude they shouldn't, yet."),
          ("Is there a minimum budget?", "The assessment is open to anyone. Detailed advisory is most useful for capital allocated at villa and townhouse level, as that's where our project coverage sits."),
          ("Do you work with business owners outside real estate?", "Yes. Marketing performance, customer acquisition, conversion and scalability — with or without a property decision attached.")],
 "band_h": "Understand the investor first. Then choose the project.",
 "band": [("/investor-assessment/", "Start your investment assessment"), ("/book/", "Talk to Ahmed")],
},
"ar": {
 "path": "/ar/", "alt": "/",
 "title": "أحمد عصمت — استشارات استثمارية في عقارات دبي والأعمال",
 "meta": "قبل أن تختار مشروعاً في دبي، حدّد هدفك ورأس مالك ومدة استثمارك. استشارات مستقلة في الفلل والتاون هاوس والمشاريع الجديدة، وفي نمو الأعمال. ابدأ تقييمك.",
 "h1": "استثمارك يبدأ من القرار، لا من المشروع",
 "lede": "لا أبدأ بعرض عقار عليك. أبدأ بفهم هدفك، ورأس مالك، ومدة استثمارك، ومستوى المخاطرة المناسب لك. بعد ذلك نحدد معاً: أين تستثمر، ومتى، ولماذا.",
 "cta1": ("/ar/investor-assessment/", "ابدأ تقييمك الاستثماري"), "cta2": ("/ar/projects/", "قارن المشاريع"),
 "cta_note": "التقييم يستغرق نحو ٤ دقائق، ولا يتطلب أي التزام.",
 "ledger": [("هل؟", "العقار أحد استخدامات رأس المال، لا الخيار التلقائي."), ("أين؟", "المجتمع والمعروض القادم يحددان العائد أكثر من التشطيب."),
            ("متى؟", "الإطلاق أو أثناء البناء أو الجاهز: لكل منها مقابل."), ("لماذا؟", "نمو، أو دخل، أو سكن للعائلة، أو تنويع.")],
 "s1_h": "لا أبدأ بالمشروع. أبدأ بالمستثمر.",
 "s1": ["<b>لا أبيعك عقاراً. أساعدك أن تقرر: هل تشتري، وأين، ومتى، ولماذا.</b>",
        "معظم رحلات الشراء في دبي تبدأ بإعلان عن مشروع جديد، ثم يحاول المشتري أن يقنع نفسه بأنه يناسبه. أنا أعكس هذا الترتيب. نبدأ بوضعك أنت: ما الذي تريد أن يحققه هذا المال، ومتى تحتاجه، وما الذي يحدث لخططك لو تأخر التسليم أو تغيّر السوق. عندها فقط يصبح اختيار المشروع قراراً واضحاً، لا رهاناً."],
 "q_h": "أربعة أسئلة قبل أي عقار",
 "q": [("هل تشتري أصلاً؟", "أحياناً يحقق المال عائداً أفضل داخل عملك الحالي، أو يحتاج إلى البقاء سائلاً. نقول ذلك بوضوح حين يكون صحيحاً."),
       ("أين تشتري؟", "المجتمع السكني، والمعروض القادم فيه، وطبيعة المستأجر أو المشتري المتوقع، كلها تحدد أداء الاستثمار أكثر من شكل الوحدة."),
       ("متى تشتري؟", "الإطلاق الأول، أو مرحلة البناء، أو الوحدة الجاهزة. لكل توقيت منطق مختلف في السعر والسيولة والمخاطرة."),
       ("لماذا تشتري؟", "نمو رأس المال، أو دخل إيجاري، أو سكن للعائلة، أو تنويع بعيد عن نشاطك التجاري. الهدف يغيّر المشروع المناسب بالكامل.")],
 "steps_h": "كيف نعمل معاً",
 "steps": [("التقييم الاستثماري", "تجيب عن أسئلة قصيرة حول رأس المال والهدف والمدة والمخاطرة وخطة الدفع."),
           ("سيناريوهات مناسبة", "نقترح عدداً محدوداً من السيناريوهات: مشاريع بعينها، أو نوع وحدة، أو توقيت، أو بديلاً غير عقاري."),
           ("مقارنة واضحة", "نقارن المشاريع المرشحة بمعايير ثابتة: المطور، والموقع، وخطة الدفع، والتسليم، والمعروض، والسيولة، والمخاطر."),
           ("قرار موثّق", "تنتهي الاستشارة بتوصية مكتوبة تشرح المنطق وراءها، حتى تتخذ قرارك وأنت تعرف لماذا.")],
 "opp_h": "الفرص التي ندرسها",
 "opp": [("/ar/villas-for-sale-dubai/", "فلل في دبي", "مجتمعات فلل جديدة وجاهزة، بخطط دفع مختلفة."),
         ("/ar/townhouses-for-sale-dubai/", "تاون هاوس", "مدخل أقل كلفة إلى المجتمعات العائلية، بمنطق إيجاري وسيولة مختلفين عن الفلل."),
         ("/ar/projects/elysian-mansions-tilal-al-ghaf/", "عقارات فاخرة", "قصور وفلل مميزة، حيث يصبح الموقع والندرة أهم من السعر للمتر."),
         ("/ar/villas-installments-dubai/", "مشاريع بالتقسيط", "مشاريع قيد الإنشاء بخطط دفع ممتدة، مع دراسة واقعية لمخاطر التسليم والسيولة.")],
 "cmp_h": "قارن المشاريع حسب ملفك، لا حسب الإعلان",
 "cmp": "لا نعطي أي مشروع درجة من عشرة، ولا نقول إن مشروعاً ما هو \"الأفضل\". المشروع الذي يناسب مستثمراً يبحث عن دخل شهري قد لا يناسب مستثمراً يبحث عن نمو رأس المال خلال خمس سنوات. كل صفحة مشروع تعرض نقاط القوة والمخاطر، ولمن يناسب، ولمن لا يناسب.",
 "nb_h": "أحياناً القرار الأفضل ليس شراء عقار",
 "nb": ["إذا كان لديك نشاط تجاري يحقق عائداً مرتفعاً على كل درهم يُستثمر فيه، فقد يكون تحسين التسويق أو رفع معدل التحويل أو توسيع الطاقة التشغيلية أنفع لك من دفعة مقدمة لفيلا. وإذا كنت تحتاج إلى السيولة خلال سنتين، فقد لا يناسبك مشروع يُسلَّم بعد أربع.",
         "لا أتعامل مع العقار كإجابة جاهزة. أتعامل معه كأحد الاستخدامات الممكنة لرأس المال، وأقارنه بالبدائل المتاحة لك أنت."],
 "bio_h": "خبرة من داخل الأعمال، لا من خلف مكتب مبيعات",
 "bio": ["عملت نحو عشر سنوات في التسويق الرقمي واكتساب العملاء وتحسين معدلات التحويل، مع شركات في العقارات الفاخرة والرعاية الصحية والتعليم والتجارة الإلكترونية. رأيت من الداخل كيف تتحول الميزانيات إلى نتائج، ومتى لا تتحول.",
         "في إحدى التجارب ارتفع معدل التحويل لدى عميل من ٢–٣٪ إلى نحو ٩٪. هذه التجربة شكّلت طريقتي في النظر إلى الاستثمار: قيمة المال تُقاس بمدى كفاءة عمله، وبما كان يمكن أن يحققه في استخدام آخر."],
 "faq_h": "أسئلة شائعة",
 "faqs": [("هل تبيع العقارات بنفسك؟", "دوري هو مساعدتك على اتخاذ القرار الصحيح. حين يقرر العميل الشراء، أوضح له بشفافية كيف تتم المعاملة ومن الجهة المرخصة المنفذة لها، وأي علاقة تجارية مرتبطة بها."),
          ("هل تضمن عائداً معيناً؟", "لا. لا أحد يستطيع ضمان عائد عقاري. ما أقدمه هو تحليل واضح للعوامل التي تؤثر في العائد والمخاطر، حتى يكون قرارك مبنياً على معلومات لا على وعود."),
          ("هل الاستشارة مناسبة لي إذا لم أكن متأكداً من رغبتي في الشراء؟", "هذا بالضبط هو الوقت الأنسب. كثير من العملاء يبدأون بسؤال \"هل أشتري؟\"، وبعضهم يقرر عدم الشراء بعد التقييم."),
          ("ما الحد الأدنى لرأس المال؟", "لا يوجد حد أدنى للتقييم الاستثماري. لكن معظم المشاريع التي ندرسها فلل وتاون هاوس، ولذلك تكون الاستشارة التفصيلية أنفع لمن لديه رأس مال مخصص لهذا المستوى."),
          ("هل تقدم استشارات لأصحاب الأعمال خارج العقار؟", "نعم. أعمل مع أصحاب الأعمال على التسويق واكتساب العملاء ومعدلات التحويل وقابلية التوسع، سواء كان لديهم نية استثمار عقاري أم لا.")],
 "band_h": "ابدأ بفهم وضعك، ثم نختار المشروع",
 "band": [("/ar/investor-assessment/", "ابدأ تقييمك الاستثماري"), ("/ar/book/", "تحدث مع أحمد")],
},
}

ASSESS = {
"en": {"path": "/investor-assessment/", "alt": "/ar/investor-assessment/",
 "title": "Investor Assessment: Find the Dubai Projects That Fit Your Profile",
 "meta": "Answer five short questions on your goal, horizon, budget and payment preference. See which Dubai villa and townhouse projects may suit you — and which may not.",
 "h1": "Build your investor profile",
 "lede": "Five short questions. You'll see which projects may fit, and you can send the profile to Ahmed for a written review.",
 "qs": [("goal", "What should this capital achieve?", [("growth", "Capital growth"), ("income", "Rental income"), ("home", "A family home"), ("diversify", "Diversify from my business"), ("unsure", "Not sure yet")]),
        ("horizon", "When might you need this money back?", [("short", "Within 2–3 years"), ("mid", "In 3–5 years"), ("long", "Not for 5+ years")]),
        ("budget", "Capital you're considering (AED)", [("b1", "Under 2M"), ("b2", "2M–5M"), ("b3", "5M–15M"), ("b4", "Over 15M")]),
        ("stage", "Preferred stage", [("ready", "Ready or near-ready"), ("offplan", "Off-plan with a payment plan"), ("any", "Open to both")]),
        ("risk", "How do you feel about handover delays?", [("low", "I need certainty"), ("mid", "I can handle some delay"), ("high", "Comfortable with a long wait")])],
 "submit": "See matching projects", "result_h": "Your preliminary profile",
 "send": "Send my profile to Ahmed on WhatsApp", "book": "Talk to Ahmed",
 "note": "This is a starting point, not advice. A written review considers your full situation.",
},
"ar": {"path": "/ar/investor-assessment/", "alt": "/investor-assessment/",
 "title": "التقييم الاستثماري: اعرف مشاريع دبي التي تناسب ملفك",
 "meta": "أجب عن خمسة أسئلة قصيرة عن هدفك ومدتك وميزانيتك وطريقة الدفع، واعرف أي مشاريع الفلل والتاون هاوس في دبي قد تناسبك وأيها لا يناسبك.",
 "h1": "ابنِ ملفك الاستثماري",
 "lede": "خمسة أسئلة قصيرة. سترى المشاريع التي قد تناسبك، ويمكنك إرسال ملفك إلى أحمد لمراجعة مكتوبة.",
 "qs": [("goal", "ما الذي تريد أن يحققه هذا المال؟", [("growth", "نمو رأس المال"), ("income", "دخل إيجاري"), ("home", "سكن للعائلة"), ("diversify", "تنويع بعيداً عن نشاطي"), ("unsure", "لست متأكداً بعد")]),
        ("horizon", "متى قد تحتاج إلى هذا المال؟", [("short", "خلال سنتين أو ثلاث"), ("mid", "خلال 3 إلى 5 سنوات"), ("long", "ليس قبل 5 سنوات")]),
        ("budget", "رأس المال الذي تفكر فيه (درهم)", [("b1", "أقل من 2 مليون"), ("b2", "من 2 إلى 5 ملايين"), ("b3", "من 5 إلى 15 مليون"), ("b4", "أكثر من 15 مليون")]),
        ("stage", "المرحلة المفضلة", [("ready", "جاهز أو شبه جاهز"), ("offplan", "قيد الإنشاء بخطة دفع"), ("any", "منفتح على الاثنين")]),
        ("risk", "ما موقفك من تأخر التسليم؟", [("low", "أحتاج إلى يقين"), ("mid", "أتحمل بعض التأخير"), ("high", "مرتاح لانتظار طويل")])],
 "submit": "اعرض المشاريع المناسبة", "result_h": "ملفك المبدئي",
 "send": "أرسل ملفي إلى أحمد على واتساب", "book": "تحدث مع أحمد",
 "note": "هذه نقطة بداية وليست نصيحة. المراجعة المكتوبة تأخذ وضعك الكامل في الاعتبار.",
},
}

BOOK = {
"en": {"path": "/book/", "alt": "/ar/book/", "title": "Talk to Ahmed — Book an Investment Consultation in Dubai",
 "meta": "Book a conversation with Ahmed Esmat about a Dubai property decision or business growth question. Start on WhatsApp or by email.",
 "h1": "Talk to Ahmed",
 "lede": "Tell me what you're weighing up — a project, a budget, a timeline, or whether to buy at all. I'll reply with the questions that matter for your situation.",
 "bring": "It helps to share", "bring_list": ["What you want the capital to achieve", "When you might need it back", "Roughly how much you're considering", "Any projects you're already looking at"],
 "wa": "Message on WhatsApp", "mail": "Send an email", "missing": "Contact details are being added. In the meantime, start with the investor assessment."},
"ar": {"path": "/ar/book/", "alt": "/book/", "title": "تحدث مع أحمد — احجز استشارة استثمارية في دبي",
 "meta": "احجز محادثة مع أحمد عصمت حول قرار عقاري في دبي أو سؤال عن نمو أعمالك. ابدأ على واتساب أو بالبريد الإلكتروني.",
 "h1": "تحدث مع أحمد",
 "lede": "أخبرني بما تفكر فيه: مشروع، أو ميزانية، أو توقيت، أو هل تشتري أصلاً. سأرد بالأسئلة المهمة لوضعك.",
 "bring": "يساعدنا أن تشارك", "bring_list": ["ما الذي تريد أن يحققه المال", "متى قد تحتاج إليه", "المبلغ التقريبي الذي تفكر فيه", "أي مشاريع تنظر إليها حالياً"],
 "wa": "راسلني على واتساب", "mail": "أرسل بريداً إلكترونياً", "missing": "يجري إضافة بيانات التواصل. حتى ذلك الحين ابدأ بالتقييم الاستثماري."},
}

DISCLAIMER = {
"en": {"path": "/disclaimer/", "alt": "/ar/disclaimer/", "title": "Disclaimer — Ahmed Esmat", "meta": "How to read the information on this site: advisory scope, data sources and limits.", "h1": "Disclaimer",
 "body": ["Ahmed Esmat provides real estate and business advisory. Content on this website is general information to help you think through a decision. It is not financial, legal or tax advice, and it is not an offer to sell any property.",
          "Project information — including unit types, stages and handover timing — is gathered from developer announcements and public sources and checked on the date shown on each page. Prices, payment plans and dates change frequently. Always confirm current details with the developer or a licensed broker before making any commitment.",
          "No return, price growth or rental income is guaranteed. Past performance of any community or developer does not predict future results.",
          "Ahmed Esmat is not affiliated with any developer named on this site unless explicitly stated. Developer and project names belong to their respective owners."]},
"ar": {"path": "/ar/disclaimer/", "alt": "/disclaimer/", "title": "إخلاء المسؤولية — أحمد عصمت", "meta": "كيف تقرأ المعلومات في هذا الموقع: نطاق الاستشارة ومصادر البيانات وحدودها.", "h1": "إخلاء المسؤولية",
 "body": ["يقدم أحمد عصمت استشارات في العقار والأعمال. المحتوى في هذا الموقع معلومات عامة تساعدك على التفكير في قرارك، وليس نصيحة مالية أو قانونية أو ضريبية، ولا عرضاً لبيع أي عقار.",
          "معلومات المشاريع، ومنها أنواع الوحدات والمراحل ومواعيد التسليم، مأخوذة من إعلانات المطورين ومصادر عامة ومراجعة بالتاريخ المذكور في كل صفحة. الأسعار وخطط الدفع والمواعيد تتغير كثيراً، فتأكد دائماً من التفاصيل الحالية مع المطور أو وسيط مرخص قبل أي التزام.",
          "لا يوجد ضمان لأي عائد أو نمو في السعر أو دخل إيجاري. الأداء السابق لأي مجتمع أو مطور لا يضمن النتائج المستقبلية.",
          "أحمد عصمت غير مرتبط بأي مطور مذكور في هذا الموقع ما لم يُذكر ذلك صراحة. أسماء المطورين والمشاريع ملك لأصحابها."]},
}
