# Project database. Rule from the strategy: a project is not published if risks or not_for are empty.
# PRICE / PAYMENT PLAN / PCT_BEFORE_HANDOVER: fill ONLY with figures verified from the developer on a known date.
# When left as None the page shows "confirmed on request" instead of a number (and the number stays out of meta tags).

PROJECTS = [
{
 "slug": "the-valley-emaar", "cats": ["villa", "townhouse", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "The Valley", "developer": "Emaar", "area": "Dubai–Al Ain Road (E66)",
  "types": "3–4 bedroom townhouses and villas", "stage": "Mixed: early phases delivered, newer clusters under construction",
  "handover": "Varies by cluster", "kw": "the valley emaar",
  "summary": "A master-planned family community by Emaar on the Dubai–Al Ain Road, built in clusters such as Eden and Nara. It is one of Emaar's lower entry points into a branded villa and townhouse community.",
  "suits": ["Families who want space and an Emaar-managed community at a lower entry price than central Emaar areas",
            "Investors with a 5+ year horizon who accept that the area is still maturing",
            "First-time villa or townhouse buyers who value a known developer"],
  "not_for": ["Anyone who needs to be within a short commute of Downtown or DIFC every day",
              "Investors who need strong rental income from day one",
              "Buyers who need to exit within 2–3 years"],
  "location": "The Valley sits on the Dubai–Al Ain Road, south-east of the city's established villa belt. Access to central Dubai is by car. Retail, schools and community facilities are being delivered in stages, so what exists today and what is planned should be checked separately before you buy. The distance is the trade-off: it keeps entry prices lower, and it is also the main question any buyer here should test against their daily routine.",
  "appreciation": ["Emaar's track record of maturing communities over time", "Infrastructure and amenities arriving as later phases complete", "Continued demand for family homes as Dubai's population grows outward"],
  "rental": "Rental data exists for completed clusters but is still thin compared with established communities. Check current listings and completed-lease data for the specific cluster, not the community average.",
  "supply": "The Valley is released in many clusters with similar unit types. That keeps the community growing, and it also means more comparable units compete when you rent or resell. Check how many units are handing over near your cluster in the same year.",
  "strengths": ["Emaar brand and community management", "Lower entry price than central Emaar communities", "Clear family positioning"],
  "risks": ["Commute distance to central Dubai", "Competition from many similar units at resale", "Community amenities still being completed in stages"],
  "faqs": [("Where is The Valley by Emaar located?", "On the Dubai–Al Ain Road (E66), south-east of central Dubai. It is a car-dependent location, so test the commute against your daily routine."),
           ("What's the difference between Nara and Eden at The Valley?", "They are separate clusters within the same master community, released at different times with different unit mixes and handover dates. Compare the specific cluster's payment plan and delivery date rather than treating The Valley as one product."),
           ("Is The Valley good for rental income?", "It can work for patient investors, but rental data is still limited and supply is high. It tends to suit capital-growth or end-user buyers better than income-first investors."),
           ("Who is The Valley not right for?", "Buyers who need a short daily commute to central Dubai, investors who need immediate rental yield, and anyone who may need to sell within two to three years.")],
  "compare": ["damac-lagoons", "nad-al-sheba-gardens"],
 },
 "ar": {
  "name": "The Valley", "developer": "إعمار", "area": "طريق دبي–العين (E66)",
  "types": "تاون هاوس وفلل من 3 إلى 4 غرف", "stage": "مختلط: مراحل مسلّمة وأخرى قيد الإنشاء",
  "handover": "يختلف حسب المجموعة",
  "summary": "مجتمع عائلي متكامل من إعمار على طريق دبي–العين، يُطرح على مجموعات مثل Eden وNara. ويُعد من أقل نقاط الدخول سعراً إلى مجتمعات إعمار للفلل والتاون هاوس.",
  "suits": ["العائلات التي تريد مساحة ومجتمعاً تديره إعمار بسعر دخول أقل من مناطق إعمار المركزية",
            "المستثمر الذي يخطط لخمس سنوات أو أكثر ويتقبل أن المنطقة ما زالت في طور النمو",
            "من يشتري أول فيلا أو تاون هاوس ويهمه اسم المطور"],
  "not_for": ["من يحتاج إلى الوصول يومياً وبسرعة إلى وسط دبي أو مركز دبي المالي",
              "المستثمر الذي يريد دخلاً إيجارياً قوياً من اليوم الأول",
              "من قد يحتاج إلى البيع خلال سنتين أو ثلاث"],
  "location": "يقع The Valley على طريق دبي–العين جنوب شرق حزام الفلل التقليدي في المدينة، والوصول إلى وسط دبي يكون بالسيارة. المدارس والمحال والخدمات تُسلَّم على مراحل، لذلك من المهم أن تفرّق بين ما هو قائم اليوم وما هو مخطط قبل الشراء. المسافة هي المقابل: هي ما يجعل سعر الدخول أقل، وهي أيضاً أول سؤال يجب أن تختبره مقابل روتينك اليومي.",
  "appreciation": ["سجل إعمار في إنضاج المجتمعات مع الوقت", "اكتمال البنية التحتية والخدمات مع تسليم المراحل اللاحقة", "استمرار الطلب على البيوت العائلية مع توسع دبي نحو الأطراف"],
  "rental": "تتوفر بيانات إيجار للمجموعات المسلّمة لكنها ما زالت محدودة مقارنة بالمجتمعات القديمة. راجع الإعلانات الحالية وعقود الإيجار الفعلية للمجموعة نفسها، لا متوسط المجتمع كله.",
  "supply": "يُطرح المشروع على مجموعات كثيرة بوحدات متشابهة. هذا يعني نمواً مستمراً للمجتمع، ويعني أيضاً منافسة أكبر عند التأجير أو إعادة البيع. اعرف كم وحدة تُسلَّم قرب مجموعتك في السنة نفسها.",
  "strengths": ["اسم إعمار وإدارتها للمجتمع", "سعر دخول أقل من مجتمعات إعمار المركزية", "طابع عائلي واضح"],
  "risks": ["المسافة إلى وسط دبي", "منافسة وحدات متشابهة كثيرة عند إعادة البيع", "خدمات المجتمع ما زالت تكتمل على مراحل"],
  "faqs": [("أين يقع مشروع The Valley من إعمار؟", "على طريق دبي–العين (E66) جنوب شرق وسط دبي. الموقع يعتمد على السيارة، لذا جرّب المسافة مقابل تنقلك اليومي."),
           ("ما الفرق بين Nara وEden في The Valley؟", "هما مجموعتان منفصلتان داخل المجتمع نفسه، طُرحتا في أوقات مختلفة وبوحدات ومواعيد تسليم مختلفة. قارن خطة الدفع وموعد التسليم للمجموعة المحددة."),
           ("هل The Valley مناسب للدخل الإيجاري؟", "قد يناسب المستثمر الصبور، لكن بيانات الإيجار ما زالت محدودة والمعروض كبير. هو أقرب إلى من يبحث عن نمو رأس المال أو السكن."),
           ("لمن لا يناسب The Valley؟", "لمن يحتاج إلى تنقل يومي قصير إلى وسط دبي، ولمن يريد عائداً إيجارياً فورياً، ولمن قد يبيع خلال سنتين أو ثلاث.")],
 },
},
{
 "slug": "damac-lagoons", "cats": ["villa", "townhouse", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "DAMAC Lagoons", "developer": "DAMAC", "area": "Dubailand, next to DAMAC Hills",
  "types": "Townhouses and villas in themed clusters", "stage": "Mixed: some clusters delivered, others under construction",
  "handover": "Varies by cluster", "kw": "damac lagoons",
  "summary": "A lagoon-themed community by DAMAC made up of clusters named after Mediterranean destinations, such as Portofino. Most stock is townhouses, with villas in selected clusters.",
  "suits": ["Buyers who want a resort-style, amenity-led community", "Investors comfortable with a developer payment plan and a multi-year hold",
            "Families looking at townhouses with lagoon and leisure amenities"],
  "not_for": ["Investors who want low supply and scarcity in their community", "Buyers who need liquidity within 2–3 years",
              "Anyone who prefers a quiet, low-density neighbourhood"],
  "location": "DAMAC Lagoons sits in Dubailand beside DAMAC Hills, with access by car to Sheikh Mohammed Bin Zayed Road and Al Qudra Road. The community is organised in themed clusters around crystal lagoons and leisure areas. Check which amenities in your chosen cluster are operating today and which are planned.",
  "appreciation": ["Amenity-led positioning that appeals to families", "Maturing of the wider Dubailand area", "Delivery of later clusters completing the community picture"],
  "rental": "Rental evidence is building as clusters hand over. Base any income assumption on actual leases in delivered clusters, not on brochure yields.",
  "supply": "DAMAC Lagoons is a large community with many similar townhouses across clusters, plus neighbouring DAMAC Hills 2 and other Dubailand projects. Supply at handover is the key risk to test.",
  "strengths": ["Distinctive lagoon and resort-style concept", "Range of townhouse and villa options", "Developer payment plans on newer releases"],
  "risks": ["High volume of similar units at handover and resale", "Car-dependent location", "Cluster-level differences in delivery timing"],
  "faqs": [("Is DAMAC Lagoons a good investment?", "It depends on your horizon and goal. It can suit buyers who value amenities and can hold for several years. The main thing to test is supply: many similar units will compete at resale."),
           ("What is DAMAC Lagoons Portofino?", "Portofino is one of the themed clusters inside DAMAC Lagoons. Each cluster has its own release date, unit mix and handover schedule, so compare them individually."),
           ("Are there villas in DAMAC Lagoons or only townhouses?", "Most units are townhouses, with villas in selected clusters. Check the current release for availability."),
           ("How does DAMAC Lagoons compare with The Valley?", "Both are family communities outside the city core. DAMAC Lagoons leans on lagoon and resort amenities; The Valley leans on Emaar's community model and a lower entry price. The better fit depends on your budget, commute and horizon.")],
  "compare": ["the-valley-emaar", "tilal-al-ghaf"],
 },
 "ar": {
  "name": "DAMAC Lagoons داماك لاجونز", "developer": "داماك", "area": "دبي لاند، بجوار داماك هيلز",
  "types": "تاون هاوس وفلل ضمن مجموعات بطابع مختلف", "stage": "مختلط: مجموعات مسلّمة وأخرى قيد الإنشاء",
  "handover": "يختلف حسب المجموعة",
  "summary": "مجتمع من داماك قائم على البحيرات، مقسّم إلى مجموعات تحمل أسماء وجهات متوسطية مثل Portofino. أغلب الوحدات تاون هاوس، مع فلل في مجموعات محددة.",
  "suits": ["من يريد مجتمعاً بطابع المنتجعات والخدمات الترفيهية", "المستثمر المرتاح لخطة دفع من المطور ولمدة احتفاظ متعددة السنوات",
            "العائلات التي تبحث عن تاون هاوس مع مرافق البحيرات والترفيه"],
  "not_for": ["المستثمر الذي يريد معروضاً محدوداً وندرة في مجتمعه", "من يحتاج إلى السيولة خلال سنتين أو ثلاث",
              "من يفضل حياً هادئاً قليل الكثافة"],
  "location": "يقع داماك لاجونز في دبي لاند بجوار داماك هيلز، ويُوصل إليه بالسيارة عبر شارع الشيخ محمد بن زايد وطريق القدرة. المجتمع مقسّم إلى مجموعات حول بحيرات صناعية ومناطق ترفيه. تأكد من المرافق العاملة اليوم في مجموعتك، ومن المرافق المخطط لها فقط.",
  "appreciation": ["طابع قائم على المرافق يجذب العائلات", "نضج منطقة دبي لاند عموماً", "اكتمال المجموعات اللاحقة وصورة المجتمع النهائية"],
  "rental": "تتكوّن بيانات الإيجار تدريجياً مع تسليم المجموعات. ابنِ أي توقع للدخل على عقود فعلية في المجموعات المسلّمة، لا على عوائد الكتيبات.",
  "supply": "المجتمع كبير وفيه تاون هاوس متشابهة كثيرة، إضافة إلى داماك هيلز 2 ومشاريع أخرى في دبي لاند. المعروض عند التسليم هو المخاطرة الأهم.",
  "strengths": ["فكرة مميزة قائمة على البحيرات والمنتجعات", "تنوع في التاون هاوس والفلل", "خطط دفع من المطور في الإصدارات الجديدة"],
  "risks": ["عدد كبير من الوحدات المتشابهة عند التسليم وإعادة البيع", "موقع يعتمد على السيارة", "اختلاف مواعيد التسليم بين المجموعات"],
  "faqs": [("هل داماك لاجونز استثمار جيد؟", "يعتمد على هدفك ومدة استثمارك. قد يناسب من يهمه نمط الحياة ويستطيع الاحتفاظ لعدة سنوات. أهم ما يجب اختباره هو المعروض، لأن وحدات متشابهة كثيرة ستنافس عند إعادة البيع."),
           ("ما هو Portofino في داماك لاجونز؟", "هو إحدى المجموعات داخل داماك لاجونز. لكل مجموعة موعد طرح ووحدات وموعد تسليم خاص بها، فقارن كل مجموعة على حدة."),
           ("هل في داماك لاجونز فلل أم تاون هاوس فقط؟", "أغلب الوحدات تاون هاوس، مع فلل في مجموعات محددة. راجع الإصدار الحالي لمعرفة المتاح."),
           ("ما الفرق بين داماك لاجونز وThe Valley؟", "كلاهما مجتمع عائلي خارج مركز المدينة. داماك لاجونز يعتمد على البحيرات ومرافق المنتجعات، وThe Valley يعتمد على نموذج إعمار وسعر دخول أقل. الأنسب يعتمد على ميزانيتك وتنقلك ومدة استثمارك.")],
 },
},
{
 "slug": "tilal-al-ghaf", "cats": ["villa", "townhouse", "luxury", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "Tilal Al Ghaf", "developer": "Majid Al Futtaim", "area": "Hessa Street / Al Khail Road corridor",
  "types": "Townhouses, villas and mansions across sub-communities", "stage": "Mixed: early sub-communities delivered, newer ones under construction",
  "handover": "Varies by sub-community", "kw": "tilal al ghaf villas",
  "summary": "A lagoon-centred community by Majid Al Futtaim built around Lagoon Al Ghaf, with sub-communities including Elan, Aura, Alaya and the Elysian Mansions.",
  "suits": ["Families who want a newer, more central community with a lagoon lifestyle", "Investors focused on long-term capital growth in a premium community",
            "Buyers who value a master developer with a strong retail and community track record"],
  "not_for": ["Buyers looking for the lowest entry price", "Income-first investors who need high gross yield",
              "Anyone uncomfortable paying a premium for location and brand"],
  "location": "Tilal Al Ghaf is positioned along the Hessa Street and Al Khail Road corridor, closer to the Dubai Marina and Al Barsha side of the city than most new villa communities. The lagoon, beach and park network sit at the centre of the master plan.",
  "appreciation": ["Relatively central location for a new villa community", "Lagoon-led amenity that is hard to replicate", "Sub-community releases moving up the price ladder over time"],
  "rental": "Delivered sub-communities provide early rental evidence. Premium pricing usually means lower gross yield than outer communities.",
  "supply": "Supply is spread across several distinct sub-communities with different product levels. Compare like-for-like within the same sub-community when assessing resale competition.",
  "strengths": ["Central positioning compared with most new villa communities", "Lagoon and beach amenity", "Clear product ladder from townhouses to mansions"],
  "risks": ["Premium entry pricing narrows the buyer pool at resale", "Lower gross rental yield than outer communities", "Timing differences between sub-communities"],
  "faqs": [("What are Elan, Aura and Alaya at Tilal Al Ghaf?", "They are separate sub-communities within Tilal Al Ghaf, each with its own design, unit mix and handover timing. Compare them individually."),
           ("Is Tilal Al Ghaf better for living or investing?", "Its strongest case is long-term capital growth and end-use for families who want a more central villa community. Income-first investors may find yields lower than in outer areas."),
           ("Where is Tilal Al Ghaf?", "Along the Hessa Street and Al Khail Road corridor, closer to Al Barsha and Dubai Marina than most new villa communities."),
           ("How does Tilal Al Ghaf compare with DAMAC Lagoons?", "Both use lagoon amenities, but Tilal Al Ghaf is more central and priced higher. DAMAC Lagoons offers a lower entry point with more units and more supply.")],
  "compare": ["damac-lagoons", "the-oasis-emaar"],
 },
 "ar": {
  "name": "تلال الغاف Tilal Al Ghaf", "developer": "ماجد الفطيم", "area": "محور شارع حصة وشارع الخيل",
  "types": "تاون هاوس وفلل وقصور ضمن مجتمعات فرعية", "stage": "مختلط: مجتمعات فرعية مسلّمة وأخرى قيد الإنشاء",
  "handover": "يختلف حسب المجتمع الفرعي",
  "summary": "مجتمع من ماجد الفطيم تتوسطه بحيرة الغاف، ويضم مجتمعات فرعية منها Elan وAura وAlaya وقصور Elysian Mansions.",
  "suits": ["العائلات التي تريد مجتمعاً جديداً أقرب إلى وسط المدينة بطابع البحيرات", "المستثمر الذي يركز على نمو رأس المال طويل المدى في مجتمع راقٍ",
            "من يهمه مطور رئيسي بسجل قوي في التجزئة والمجتمعات"],
  "not_for": ["من يبحث عن أقل سعر دخول", "المستثمر الذي يريد عائداً إيجارياً مرتفعاً أولاً",
              "من لا يتقبل دفع علاوة مقابل الموقع والاسم"],
  "location": "يقع تلال الغاف على محور شارع حصة وشارع الخيل، وهو أقرب إلى البرشاء ودبي مارينا من معظم مجتمعات الفلل الجديدة. البحيرة والشاطئ والحدائق في قلب المخطط العام.",
  "appreciation": ["موقع مركزي نسبياً لمجتمع فلل جديد", "بحيرة يصعب تكرارها في مشاريع أخرى", "ارتفاع تدريجي في مستوى المنتج مع كل مجتمع فرعي جديد"],
  "rental": "المجتمعات الفرعية المسلّمة تعطي أولى بيانات الإيجار. السعر المرتفع يعني عادة عائداً إجمالياً أقل من المجتمعات الأبعد.",
  "supply": "المعروض موزع على مجتمعات فرعية بمستويات مختلفة. قارن الوحدات المتشابهة داخل المجتمع الفرعي نفسه عند تقييم منافسة إعادة البيع.",
  "strengths": ["موقع أقرب إلى المركز من معظم مجتمعات الفلل الجديدة", "بحيرة وشاطئ داخل المجتمع", "تدرج واضح من التاون هاوس إلى القصور"],
  "risks": ["سعر الدخول المرتفع يقلل عدد المشترين عند إعادة البيع", "عائد إيجاري إجمالي أقل من المجتمعات الأبعد", "اختلاف التوقيت بين المجتمعات الفرعية"],
  "faqs": [("ما هي Elan وAura وAlaya في تلال الغاف؟", "مجتمعات فرعية منفصلة داخل تلال الغاف، لكل منها تصميمها ووحداتها وموعد تسليمها. قارن كلاً منها على حدة."),
           ("هل تلال الغاف أنسب للسكن أم للاستثمار؟", "أقوى ما فيه نمو رأس المال على المدى الطويل والسكن العائلي في مجتمع أقرب إلى المركز. من يبحث عن الدخل أولاً قد يجد العائد أقل من المناطق الأبعد."),
           ("أين يقع تلال الغاف؟", "على محور شارع حصة وشارع الخيل، أقرب إلى البرشاء ودبي مارينا من معظم مجتمعات الفلل الجديدة."),
           ("ما الفرق بين تلال الغاف وداماك لاجونز؟", "كلاهما يعتمد على البحيرات، لكن تلال الغاف أقرب إلى المركز وأعلى سعراً، وداماك لاجونز مدخل أقل كلفة بمعروض أكبر.")],
 },
},
{
 "slug": "elysian-mansions-tilal-al-ghaf", "cats": ["villa", "luxury", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "Elysian Mansions", "developer": "Majid Al Futtaim", "area": "Tilal Al Ghaf",
  "types": "Large luxury mansions", "stage": "Confirm current stage with the developer",
  "handover": "Confirm with the developer", "kw": "elysian mansions tilal al ghaf",
  "summary": "The top tier of Tilal Al Ghaf: a limited collection of large mansions positioned around the community's lagoon and green spaces. Search interest has grown sharply over the past year.",
  "suits": ["Buyers seeking a family residence at the top of a new master community", "Long-horizon investors buying scarcity rather than yield",
            "High-net-worth buyers diversifying into prime Dubai real estate"],
  "not_for": ["Anyone who needs rental income to cover costs", "Buyers who may need to sell quickly — the buyer pool at this level is small",
              "Investors who compare purely on price per square foot"],
  "location": "Elysian Mansions sit within Tilal Al Ghaf, which puts them on the Hessa Street and Al Khail Road corridor with the community's lagoon, parks and trails as the main amenity.",
  "appreciation": ["Limited number of mansions in the community", "Position at the top of a maturing master plan", "Demand from high-net-worth relocation to Dubai"],
  "rental": "Reliable rental data for mansions at this level is scarce. Treat this as a capital and lifestyle purchase, not an income asset.",
  "supply": "The mansion collection itself is small. The real competition comes from other prime villa locations such as Palm Jumeirah, Emirates Hills and newer ultra-prime launches.",
  "strengths": ["Scarcity within a lagoon-led community", "Prime position in Tilal Al Ghaf", "Strong brand of the master developer"],
  "risks": ["Very small buyer pool at resale", "Low or unproven rental yield", "Prime segment is more sensitive to global wealth cycles"],
  "faqs": [("What are Elysian Mansions?", "A limited collection of large luxury mansions within Tilal Al Ghaf by Majid Al Futtaim."),
           ("Are Elysian Mansions a good investment?", "They suit long-horizon buyers purchasing scarcity and lifestyle. They are not an income investment, and resale depends on a small pool of high-net-worth buyers."),
           ("How do Elysian Mansions compare with Palm Jebel Ali villas?", "Elysian Mansions are inland around a lagoon in a more central community; Palm Jebel Ali villas are beachfront on a new island still being delivered. Both are prime, long-horizon purchases with small buyer pools.")],
  "compare": ["palm-jebel-ali-villas", "tilal-al-ghaf"],
 },
 "ar": {
  "name": "Elysian Mansions", "developer": "ماجد الفطيم", "area": "تلال الغاف",
  "types": "قصور فاخرة كبيرة", "stage": "تأكد من المرحلة الحالية مع المطور",
  "handover": "يُؤكد مع المطور",
  "summary": "الفئة الأعلى في تلال الغاف: مجموعة محدودة من القصور الكبيرة حول البحيرة والمساحات الخضراء. واهتمام البحث بها ارتفع بشكل كبير خلال العام الماضي.",
  "suits": ["من يبحث عن سكن عائلي في أعلى فئة داخل مجتمع جديد", "المستثمر طويل المدى الذي يشتري الندرة لا العائد",
            "أصحاب الثروات الذين ينوّعون في عقارات دبي الفاخرة"],
  "not_for": ["من يحتاج إلى دخل إيجاري يغطي التكاليف", "من قد يحتاج إلى البيع بسرعة، فعدد المشترين في هذه الفئة قليل",
              "من يقارن فقط على أساس السعر للقدم المربع"],
  "location": "تقع القصور داخل تلال الغاف على محور شارع حصة وشارع الخيل، والبحيرة والحدائق والمسارات هي المرفق الأساسي.",
  "appreciation": ["عدد محدود من القصور داخل المجتمع", "موقع في أعلى مخطط عام ما زال ينضج", "طلب من أصحاب الثروات الذين ينتقلون إلى دبي"],
  "rental": "بيانات الإيجار الموثوقة للقصور في هذا المستوى نادرة. تعامل معه كشراء لرأس المال ونمط الحياة، لا كأصل للدخل.",
  "supply": "مجموعة القصور نفسها صغيرة. المنافسة الحقيقية من مواقع فاخرة أخرى مثل نخلة جميرا وتلال الإمارات والإطلاقات الفاخرة الجديدة.",
  "strengths": ["الندرة داخل مجتمع قائم على البحيرة", "موقع مميز داخل تلال الغاف", "قوة اسم المطور الرئيسي"],
  "risks": ["عدد قليل جداً من المشترين عند إعادة البيع", "عائد إيجاري منخفض أو غير مثبت", "الفئة الفاخرة أكثر تأثراً بدورات الثروة العالمية"],
  "faqs": [("ما هي Elysian Mansions؟", "مجموعة محدودة من القصور الفاخرة داخل تلال الغاف من ماجد الفطيم."),
           ("هل Elysian Mansions استثمار جيد؟", "تناسب من يشتري الندرة ونمط الحياة على مدى طويل. ليست استثماراً للدخل، وإعادة البيع تعتمد على عدد محدود من المشترين."),
           ("ما الفرق بين Elysian Mansions وفلل نخلة جبل علي؟", "Elysian Mansions داخل مجتمع أقرب إلى المركز حول بحيرة، وفلل نخلة جبل علي على الشاطئ في جزيرة جديدة ما زالت تُسلَّم. كلاهما شراء فاخر طويل المدى.")],
 },
},
{
 "slug": "palm-jebel-ali-villas", "cats": ["villa", "luxury", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "Palm Jebel Ali villas", "developer": "Nakheel", "area": "Palm Jebel Ali",
  "types": "Beachfront villas, including 5–6 bedroom (Beach Collection) and 6–7 bedroom (Coral Collection)", "stage": "Under construction; phased handover",
  "handover": "Phased from late 2026 through 2027 (developer announcement, Aug 2026)", "kw": "palm jebel ali villas",
  "summary": "Nakheel's relaunched island off Jebel Ali: seven islands and 16 fronds with beachfront villas. In August 2026 Nakheel released 44 villas on Frond F and said phased handovers of the first villas start in late 2026.",
  "suits": ["Long-horizon buyers who want beachfront land on a new island", "High-net-worth buyers comfortable with a multi-year build-out",
            "Investors who accept that community amenities will arrive over many years"],
  "not_for": ["Anyone who needs a finished, fully serviced community soon after handover", "Investors who need rental income early",
              "Buyers who need to exit within a few years"],
  "location": "Palm Jebel Ali lies off the coast near Jebel Ali, south-west of Dubai Marina. Nakheel has said the island will open in phases rather than on a single date, with a planned retail centre and mosque among the first community infrastructure.",
  "appreciation": ["Beachfront scarcity in Dubai", "Pricing gap versus Palm Jumeirah that early buyers are betting on", "Infrastructure delivery turning a site into a community"],
  "rental": "No rental history exists yet. The Palm Jumeirah comparison is often made, but Palm Jumeirah took many years after first handover to mature. Assume a long ramp-up.",
  "supply": "Nakheel is releasing villas frond by frond. Watch how many villas on neighbouring fronds hand over in the same period as yours.",
  "strengths": ["Direct beach access on a new island", "Large master developer backed by Dubai Holding", "Construction progressing, with phased handovers announced"],
  "risks": ["Long ramp-up before the island feels complete", "Handover dates are targets and can move", "Small buyer pool at this price level"],
  "faqs": [("When will Palm Jebel Ali villas be handed over?", "Nakheel announced in August 2026 that phased handover of the first villas starts in late 2026 and continues through 2027. Treat dates as targets and confirm the date for your specific frond."),
           ("What types of villas are on Palm Jebel Ali?", "Nakheel's recent releases include the Beach Collection with five- and six-bedroom villas and the Coral Collection with six- and seven-bedroom villas."),
           ("Is Palm Jebel Ali like Palm Jumeirah?", "It follows the same island concept, but it is at a much earlier stage. Palm Jumeirah took many years after first handover to build its full infrastructure."),
           ("Who should not buy on Palm Jebel Ali now?", "Anyone who needs income soon, a finished community on handover, or the option to sell quickly.")],
  "compare": ["elysian-mansions-tilal-al-ghaf", "the-oasis-emaar"],
 },
 "ar": {
  "name": "فلل نخلة جبل علي", "developer": "النخيل العقارية", "area": "نخلة جبل علي",
  "types": "فلل شاطئية، منها 5–6 غرف (Beach Collection) و6–7 غرف (Coral Collection)", "stage": "قيد الإنشاء، والتسليم على مراحل",
  "handover": "على مراحل من أواخر 2026 حتى 2027 (إعلان المطور، أغسطس 2026)",
  "summary": "الجزيرة التي أعادت نخيل إطلاقها قرب جبل علي: سبع جزر و16 سعفة بفلل على الشاطئ. في أغسطس 2026 طرحت نخيل 44 فيلا على السعفة F، وأعلنت أن تسليم أولى الفلل يبدأ على مراحل من أواخر 2026.",
  "suits": ["المشتري طويل المدى الذي يريد أرضاً على الشاطئ في جزيرة جديدة", "أصحاب الثروات المرتاحون لمرحلة بناء تمتد سنوات",
            "المستثمر الذي يتقبل أن خدمات المجتمع ستصل على مدى سنوات"],
  "not_for": ["من يحتاج إلى مجتمع مكتمل الخدمات بعد التسليم مباشرة", "المستثمر الذي يحتاج إلى دخل إيجاري مبكر",
              "من يحتاج إلى البيع خلال سنوات قليلة"],
  "location": "تقع نخلة جبل علي قبالة الساحل قرب جبل علي، جنوب غرب دبي مارينا. أعلنت نخيل أن الجزيرة ستُفتتح على مراحل لا في تاريخ واحد، ومن أوائل المرافق المخطط لها مركز تجاري ومسجد جامع.",
  "appreciation": ["ندرة العقارات الشاطئية في دبي", "الفارق السعري مقارنة بنخلة جميرا الذي يراهن عليه المشترون الأوائل", "تحول الموقع إلى مجتمع مع اكتمال البنية التحتية"],
  "rental": "لا يوجد سجل إيجاري بعد. كثيراً ما تُعقد المقارنة مع نخلة جميرا، لكنها احتاجت سنوات طويلة بعد أول تسليم لتنضج. افترض فترة نضج طويلة.",
  "supply": "تطرح نخيل الفلل سعفة بعد سعفة. راقب عدد الفلل التي تُسلَّم في السعف المجاورة في الفترة نفسها.",
  "strengths": ["وصول مباشر إلى الشاطئ في جزيرة جديدة", "مطور رئيسي كبير ضمن دبي القابضة", "تقدم في البناء مع إعلان تسليم على مراحل"],
  "risks": ["فترة طويلة قبل أن تكتمل الجزيرة كمجتمع", "مواعيد التسليم أهداف وقد تتغير", "عدد محدود من المشترين في هذا المستوى السعري"],
  "faqs": [("متى تُسلَّم فلل نخلة جبل علي؟", "أعلنت نخيل في أغسطس 2026 أن تسليم أولى الفلل يبدأ على مراحل من أواخر 2026 ويستمر خلال 2027. تعامل مع المواعيد كأهداف وتأكد من موعد سعفتك."),
           ("ما أنواع الفلل في نخلة جبل علي؟", "من الإصدارات الأخيرة Beach Collection بفلل من 5 و6 غرف، وCoral Collection بفلل من 6 و7 غرف."),
           ("هل نخلة جبل علي مثل نخلة جميرا؟", "الفكرة نفسها، لكنها في مرحلة أبكر بكثير. نخلة جميرا احتاجت سنوات طويلة بعد أول تسليم لتكتمل بنيتها."),
           ("لمن لا يناسب الشراء في نخلة جبل علي الآن؟", "لمن يحتاج إلى دخل قريب، أو مجتمع مكتمل عند التسليم، أو إمكانية البيع السريع.")],
 },
},
{
 "slug": "the-oasis-emaar", "cats": ["villa", "luxury", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "The Oasis", "developer": "Emaar", "area": "Dubailand, off Sheikh Zayed Bin Hamdan Al Nahyan Street",
  "types": "4–6 bedroom villas and mansions (Palmiera, Mirage, Lavita and others)", "stage": "Under construction, launched in 2023",
  "handover": "Varies by sub-community — confirm with Emaar", "kw": "the oasis emaar",
  "summary": "Emaar's waterfront villa and mansion community in Dubailand, launched in 2023, with sub-communities such as Palmiera, Mirage and Lavita set around lagoons, canals and parks.",
  "suits": ["Families wanting large new villas in an Emaar master community", "Investors with a 5+ year horizon focused on capital growth",
            "Buyers who prefer water and green-space amenity over a central location"],
  "not_for": ["Buyers who need a finished community soon", "Income-first investors", "Anyone who wants a short commute to the business districts"],
  "location": "The Oasis is in Dubailand, with access via Sheikh Zayed Bin Hamdan Al Nahyan Street, Al Yalayis Road and Expo Road. It is further out than Dubai Hills or Tilal Al Ghaf, and positioned around water and park amenity.",
  "appreciation": ["Emaar's master-planning track record", "Waterfront villa product at a lower price point than central waterfront", "Infrastructure growth in the Expo and Dubailand corridor"],
  "rental": "Reliable rental data for The Oasis does not exist yet because handovers are still ahead. Nearby Dubailand villa rents give context only.",
  "supply": "The Oasis is a very large community with thousands of homes released in phases. Watch the number of similar villas handing over in the same year.",
  "strengths": ["Large villas with water and park amenity", "Emaar brand and management", "Range of sub-communities and price levels"],
  "risks": ["Long delivery horizon for the full community", "Large future supply of similar villas", "Location further from central Dubai"],
  "faqs": [("Where is The Oasis by Emaar?", "In Dubailand, with access via Sheikh Zayed Bin Hamdan Al Nahyan Street, Al Yalayis Road and Expo Road."),
           ("What is Mira Oasis — is it the same as The Oasis?", "No. Mira Oasis is an older Emaar townhouse community in Reem. The Oasis is a newer villa and mansion community in Dubailand launched in 2023."),
           ("Is The Oasis good for rental income?", "It is too early to say — handovers are still ahead. It currently suits capital-growth and end-use buyers better than income investors."),
           ("What sub-communities are in The Oasis?", "Releases include Palmiera, Mirage and Lavita, each with different villa sizes and timing.")],
  "compare": ["tilal-al-ghaf", "palm-jebel-ali-villas"],
 },
 "ar": {
  "name": "The Oasis", "developer": "إعمار", "area": "دبي لاند، قرب شارع الشيخ زايد بن حمدان آل نهيان",
  "types": "فلل وقصور من 4 إلى 6 غرف (Palmiera وMirage وLavita وغيرها)", "stage": "قيد الإنشاء، أُطلق في 2023",
  "handover": "يختلف حسب المجتمع الفرعي، يُؤكد مع إعمار",
  "summary": "مجتمع فلل وقصور على الواجهة المائية من إعمار في دبي لاند، أُطلق في 2023، ويضم مجتمعات فرعية مثل Palmiera وMirage وLavita حول البحيرات والقنوات والحدائق.",
  "suits": ["العائلات التي تريد فللاً كبيرة جديدة داخل مجتمع من إعمار", "المستثمر الذي يخطط لخمس سنوات أو أكثر ويركز على نمو رأس المال",
            "من يفضل المياه والمساحات الخضراء على الموقع المركزي"],
  "not_for": ["من يحتاج إلى مجتمع مكتمل قريباً", "المستثمر الذي يريد الدخل أولاً", "من يريد تنقلاً قصيراً إلى مناطق الأعمال"],
  "location": "يقع The Oasis في دبي لاند، ويُوصل إليه عبر شارع الشيخ زايد بن حمدان آل نهيان وشارع اليلايس وطريق إكسبو. هو أبعد من دبي هيلز وتلال الغاف، ويعتمد على المياه والحدائق.",
  "appreciation": ["سجل إعمار في المخططات الكبرى", "فلل على الماء بسعر أقل من الواجهات المائية المركزية", "نمو البنية التحتية في محور إكسبو ودبي لاند"],
  "rental": "لا تتوفر بعد بيانات إيجار موثوقة لـ The Oasis لأن التسليم ما زال قادماً. إيجارات فلل دبي لاند القريبة للاستئناس فقط.",
  "supply": "المجتمع كبير جداً وفيه آلاف الوحدات تُطرح على مراحل. راقب عدد الفلل المتشابهة التي تُسلَّم في السنة نفسها.",
  "strengths": ["فلل كبيرة مع مياه وحدائق", "اسم إعمار وإدارتها", "تنوع المجتمعات الفرعية والمستويات السعرية"],
  "risks": ["أفق طويل لاكتمال المجتمع كله", "معروض مستقبلي كبير من فلل متشابهة", "موقع أبعد عن وسط دبي"],
  "faqs": [("أين يقع The Oasis من إعمار؟", "في دبي لاند، مع وصول عبر شارع الشيخ زايد بن حمدان آل نهيان وشارع اليلايس وطريق إكسبو."),
           ("هل ميرا أوايسس هو نفسه The Oasis؟", "لا. ميرا أوايسس مجتمع تاون هاوس أقدم من إعمار في منطقة ريم، أما The Oasis فمجتمع فلل وقصور جديد في دبي لاند أُطلق في 2023."),
           ("هل The Oasis مناسب للدخل الإيجاري؟", "من المبكر الحكم، فالتسليم ما زال قادماً. هو حالياً أنسب لمن يبحث عن نمو رأس المال أو السكن."),
           ("ما المجتمعات الفرعية في The Oasis؟", "منها Palmiera وMirage وLavita، ولكل منها مساحات ومواعيد مختلفة.")],
 },
},
{
 "slug": "nad-al-sheba-gardens", "cats": ["villa", "townhouse", "offplan"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "Nad Al Sheba Gardens", "developer": "Meraas", "area": "Nad Al Sheba, near Meydan",
  "types": "3–5 bedroom villas and 3 bedroom townhouses (Phase 3)", "stage": "Phased; confirm the current phase's status",
  "handover": "Varies by phase — confirm with Meraas", "kw": "nad al sheba gardens phase 3",
  "summary": "A gated villa and townhouse community by Meraas in Nad Al Sheba, close to Meydan and Mohammed Bin Rashid City, with access to Al Ain Road and Sheikh Mohammed Bin Zayed Road.",
  "suits": ["Families who want a central, gated community close to Downtown", "Investors who value location over lagoon-style amenities",
            "Buyers who prefer a smaller, more private community"],
  "not_for": ["Buyers looking for the lowest price per square foot", "Anyone who wants a resort-style amenity package",
              "Investors who need a quick exit"],
  "location": "Nad Al Sheba sits between Meydan and Mohammed Bin Rashid City, close to Al Ain Road and Sheikh Mohammed Bin Zayed Road, which makes it one of the more central new villa options.",
  "appreciation": ["Central location close to Downtown and Meydan", "Established surrounding neighbourhoods", "Gated, lower-density community"],
  "rental": "Check rents in completed phases and nearby Nad Al Sheba villas. Central location usually supports tenant demand.",
  "supply": "Supply is released phase by phase. Compare Phase 3 units against earlier phases on resale.",
  "strengths": ["Central location", "Gated, family-oriented community", "Meraas brand"],
  "risks": ["Higher entry price than outer communities", "Fewer headline amenities than lagoon communities", "Resale competition from earlier phases"],
  "faqs": [("Where is Nad Al Sheba Gardens?", "In Nad Al Sheba, between Meydan and Mohammed Bin Rashid City, near Al Ain Road and Sheikh Mohammed Bin Zayed Road."),
           ("What is in Nad Al Sheba Gardens Phase 3?", "Phase 3 includes 3, 4 and 5 bedroom villas and 3 bedroom townhouses."),
           ("How does Nad Al Sheba Gardens compare with The Valley?", "Nad Al Sheba Gardens is far more central and priced higher; The Valley offers a lower entry point further out on the Dubai–Al Ain Road.")],
  "compare": ["the-valley-emaar", "sobha-hartland-villas"],
 },
 "ar": {
  "name": "حدائق ند الشبا Nad Al Sheba Gardens", "developer": "مِراس", "area": "ند الشبا، قرب ميدان",
  "types": "فلل من 3 إلى 5 غرف وتاون هاوس 3 غرف (المرحلة 3)", "stage": "على مراحل، تأكد من حالة المرحلة الحالية",
  "handover": "يختلف حسب المرحلة، يُؤكد مع مِراس",
  "summary": "مجتمع مسوّر للفلل والتاون هاوس من مِراس في ند الشبا، قريب من ميدان ومدينة محمد بن راشد، مع وصول إلى طريق العين وشارع الشيخ محمد بن زايد.",
  "suits": ["العائلات التي تريد مجتمعاً مسوّراً قريباً من وسط دبي", "المستثمر الذي يقدّم الموقع على مرافق البحيرات",
            "من يفضل مجتمعاً أصغر وأكثر خصوصية"],
  "not_for": ["من يبحث عن أقل سعر للقدم المربع", "من يريد مرافق بطابع المنتجعات", "المستثمر الذي يحتاج إلى خروج سريع"],
  "location": "تقع ند الشبا بين ميدان ومدينة محمد بن راشد، قرب طريق العين وشارع الشيخ محمد بن زايد، وهي من أكثر خيارات الفلل الجديدة قرباً من المركز.",
  "appreciation": ["موقع مركزي قريب من وسط دبي وميدان", "أحياء محيطة مكتملة", "مجتمع مسوّر أقل كثافة"],
  "rental": "راجع الإيجارات في المراحل المكتملة وفلل ند الشبا القريبة. الموقع المركزي يدعم الطلب عادة.",
  "supply": "المعروض يُطرح مرحلة بعد مرحلة. قارن وحدات المرحلة 3 بالمراحل السابقة عند إعادة البيع.",
  "strengths": ["موقع مركزي", "مجتمع عائلي مسوّر", "اسم مِراس"],
  "risks": ["سعر دخول أعلى من المجتمعات الأبعد", "مرافق أقل بروزاً من مجتمعات البحيرات", "منافسة المراحل السابقة عند إعادة البيع"],
  "faqs": [("أين تقع حدائق ند الشبا؟", "في ند الشبا بين ميدان ومدينة محمد بن راشد، قرب طريق العين وشارع الشيخ محمد بن زايد."),
           ("ماذا تضم المرحلة 3 من حدائق ند الشبا؟", "فللاً من 3 و4 و5 غرف وتاون هاوس من 3 غرف."),
           ("ما الفرق بين حدائق ند الشبا وThe Valley؟", "حدائق ند الشبا أقرب بكثير إلى المركز وأعلى سعراً، وThe Valley مدخل أقل كلفة وأبعد على طريق دبي–العين.")],
 },
},
{
 "slug": "sobha-hartland-villas", "cats": ["villa", "luxury"],
 "price_from": None, "payment_plan": None, "pct_before_handover": None,
 "en": {
  "name": "Sobha Hartland villas", "developer": "Sobha Realty", "area": "Mohammed Bin Rashid Al Maktoum City (MBR City)",
  "types": "Villas in Sobha Hartland and Sobha Hartland II", "stage": "Mixed: completed villas and newer phases",
  "handover": "Completed villas available; newer phases vary", "kw": "sobha hartland villas dubai",
  "summary": "Sobha Realty's villa offering in MBR City, close to Downtown and Ras Al Khor, known for the developer's in-house construction and finishing.",
  "suits": ["Buyers who want a ready or near-ready villa close to Downtown", "Families prioritising build quality and central location",
            "Investors who prefer lower delivery risk over off-plan pricing"],
  "not_for": ["Buyers looking for the lowest entry price", "Anyone who wants a large-plot, low-density suburban feel",
              "Investors seeking launch-stage pricing"],
  "location": "Sobha Hartland sits in MBR City, a short drive from Downtown Dubai, Business Bay and Ras Al Khor, with schools inside the community.",
  "appreciation": ["Central location near Downtown", "Developer's reputation for build quality", "Maturing MBR City district"],
  "rental": "Completed villas provide real rental evidence. Use current leases in Hartland rather than district averages.",
  "supply": "Sobha Hartland II and other MBR City projects add supply over time. Check nearby handovers in your target year.",
  "strengths": ["Central location", "Completed stock with rental evidence", "Strong reputation for finishing"],
  "risks": ["Premium pricing", "Smaller plots than suburban villa communities", "Ongoing supply from Hartland II and MBR City"],
  "faqs": [("Where are Sobha Hartland villas?", "In Mohammed Bin Rashid Al Maktoum City (MBR City), close to Downtown Dubai and Ras Al Khor."),
           ("Are Sobha Hartland villas ready or off-plan?", "Both exist: completed villas in Sobha Hartland and newer phases, including Sobha Hartland II."),
           ("Who suits Sobha Hartland?", "Buyers who want a central villa with lower delivery risk and are willing to pay for location and build quality.")],
  "compare": ["nad-al-sheba-gardens", "tilal-al-ghaf"],
 },
 "ar": {
  "name": "فلل شوبا هارتلاند", "developer": "شوبا العقارية", "area": "مدينة محمد بن راشد آل مكتوم",
  "types": "فلل في شوبا هارتلاند وشوبا هارتلاند 2", "stage": "مختلط: فلل مكتملة ومراحل أحدث",
  "handover": "فلل جاهزة متاحة، والمراحل الأحدث تختلف",
  "summary": "فلل شوبا العقارية في مدينة محمد بن راشد، قريبة من وسط دبي ورأس الخور، ومعروفة بتنفيذ المطور للبناء والتشطيب بنفسه.",
  "suits": ["من يريد فيلا جاهزة أو شبه جاهزة قريبة من وسط دبي", "العائلات التي تضع جودة البناء والموقع المركزي أولاً",
            "المستثمر الذي يفضل مخاطر تسليم أقل على أسعار ما قبل الإنشاء"],
  "not_for": ["من يبحث عن أقل سعر دخول", "من يريد أرضاً كبيرة وطابع الضواحي الهادئ", "من يبحث عن أسعار الإطلاق الأولى"],
  "location": "يقع شوبا هارتلاند في مدينة محمد بن راشد، على بعد مسافة قصيرة بالسيارة من وسط دبي والخليج التجاري ورأس الخور، وفيه مدارس داخل المجتمع.",
  "appreciation": ["موقع مركزي قرب وسط دبي", "سمعة المطور في جودة البناء", "نضج منطقة مدينة محمد بن راشد"],
  "rental": "الفلل المكتملة تعطي بيانات إيجار حقيقية. اعتمد على عقود هارتلاند الحالية لا على متوسط المنطقة.",
  "supply": "شوبا هارتلاند 2 ومشاريع أخرى في المنطقة تضيف معروضاً مع الوقت. راجع التسليمات القريبة في السنة التي تستهدفها.",
  "strengths": ["موقع مركزي", "وحدات مكتملة مع بيانات إيجار", "سمعة قوية في التشطيب"],
  "risks": ["سعر مرتفع", "مساحات أراضٍ أصغر من مجتمعات الضواحي", "معروض مستمر من هارتلاند 2 والمنطقة"],
  "faqs": [("أين تقع فلل شوبا هارتلاند؟", "في مدينة محمد بن راشد آل مكتوم، قرب وسط دبي ورأس الخور."),
           ("هل فلل شوبا هارتلاند جاهزة أم قيد الإنشاء؟", "يوجد الاثنان: فلل مكتملة في شوبا هارتلاند ومراحل أحدث منها شوبا هارتلاند 2."),
           ("لمن تناسب شوبا هارتلاند؟", "لمن يريد فيلا في موقع مركزي بمخاطر تسليم أقل، ومستعد لدفع مقابل الموقع وجودة البناء.")],
 },
},
]

BY_SLUG = {p["slug"]: p for p in PROJECTS}
for p in PROJECTS:
    for lang in ("en", "ar"):
        assert p[lang]["risks"] and p[lang]["not_for"], f"{p['slug']} {lang}: risks/not_for required"
